// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sobkbprkndnciyzwqkzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvYmticHJrbmRuY2l5endxa3pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTE0NzMsImV4cCI6MjA2NDQ2NzQ3M30.SbZ4rmV9puMuegSk1IZCQtrNNZt0kPLFqBIfSyL6VYM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);